'use client';
import{useEffect,useState,type FormEvent}from'react';import Link from'next/link';import{useRouter}from'next/navigation';import{api}from'../lib/api';
type Finance={revenue:string;received:string;refunds:string;netCash:string;partCost:string;operatingExpenses:string;contributionAfterExpenses:string;basis:string};
export default function Reports(){const router=useRouter();const[finance,setFinance]=useState<Finance|null>(null);const[tech,setTech]=useState<{id:string;firstName:string;assigned:number;completed:number;repairSeconds:number}[]>([]);const[error,setError]=useState('');
function fail(e:unknown){if(e instanceof Error&&e.message==='SESSION_EXPIRED')router.replace('/login');else setError(e instanceof Error?e.message:'Xato')}
async function load(from?:string,to?:string){const q=from&&to?'?from='+encodeURIComponent(from)+'&to='+encodeURIComponent(to):'';setFinance(await api('/reports/finance'+q));setTech(await api('/reports/technicians'))}
useEffect(()=>{load().catch(fail)},[]);
return <main className="page"><header><Link href="/dashboard" className="brand">MY SERVICE</Link><Link href="/orders">Buyurtmalar</Link></header><div className="title-row"><div><p className="eyebrow">NATIJALAR</p><h1>Hisobotlar</h1></div><form className="inline-form" onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);load(String(d.get('from')),String(d.get('to'))).catch(fail)}}><input name="from" type="date" required/><input name="to" type="date" required/><button>Ko‘rsatish</button></form></div>{error&&<p className="error">{error}</p>}
{finance&&<><div className="cards">{[['Tushum',finance.revenue],['Kelgan pul',finance.received],['Refund',finance.refunds],['Sof pul oqimi',finance.netCash],['Detal tannarxi',finance.partCost],['Operatsion xarajat',finance.operatingExpenses],['Hissa',finance.contributionAfterExpenses]].map(([k,v])=><section key={k}><span className="muted">{k}</span><strong>{Number(v).toLocaleString('uz-UZ')}</strong></section>)}</div><p className="muted">{finance.basis}</p></>}
<section><h2>Ustalar</h2><div className="table-scroll"><table><thead><tr><th>Usta</th><th>Biriktirilgan</th><th>Topshirilgan</th><th>Ish vaqti</th></tr></thead><tbody>{tech.map(t=><tr key={t.id}><td>{t.firstName}</td><td>{t.assigned}</td><td>{t.completed}</td><td>{Math.round(t.repairSeconds/60)} min</td></tr>)}</tbody></table></div></section></main>}