'use client';
import{useEffect,useState,type FormEvent}from'react';import Link from'next/link';import{useRouter}from'next/navigation';import{api}from'../lib/api';
type Branch={id:string;name:string};type Template={id:string;type:string;channel:string;body:string;active:boolean};type Audit={id:string;action:string;entityId:string|null;createdAt:string};type Method={id:string;key:string;label:string};type Sub={status:string;expiresAt:string;plan:{name:string;features:Record<string,boolean>}};
export default function Settings(){const router=useRouter();const[branches,setBranches]=useState<Branch[]>([]);const[templates,setTemplates]=useState<Template[]>([]);const[methods,setMethods]=useState<Method[]>([]);const[audit,setAudit]=useState<Audit[]>([]);const[sub,setSub]=useState<Sub|null>(null);const[error,setError]=useState('');const[busy,setBusy]=useState(false);
function fail(e:unknown){if(e instanceof Error&&e.message==='SESSION_EXPIRED')router.replace('/login');else setError(e instanceof Error?e.message:'Xato')}
async function load(){setBranches(await api('/branches'));setTemplates(await api('/settings/notifications'));setMethods(await api('/settings/payment-methods'));setAudit(await api('/settings/audit'));setSub(await api('/settings/subscription'))}useEffect(()=>{load().catch(fail)},[]);
async function send(e:FormEvent<HTMLFormElement>,path:string,body:(d:FormData)=>unknown){e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');try{await api(path,{method:path==='/branches'?'POST':'PUT',body:JSON.stringify(body(new FormData(form)))});form.reset();await load()}catch(e){fail(e)}finally{setBusy(false)}}
return <main className="page"><header><Link href="/dashboard" className="brand">MY SERVICE</Link><Link href="/orders">Buyurtmalar</Link></header><h1>Sozlamalar</h1>{error&&<p className="error">{error}</p>}{sub&&<section><h2>{sub.plan.name}</h2><p>{sub.status} · {new Date(sub.expiresAt).toLocaleDateString('uz-UZ')} gacha</p><p className="muted">{Object.entries(sub.plan.features).filter(([,v])=>v).map(([k])=>k).join(', ')}</p></section>}
<div className="detail-grid" style={{marginTop:24}}><section><h2>Filiallar</h2>{branches.map(b=><p key={b.id}>{b.name}</p>)}<form onSubmit={e=>send(e,'/branches',d=>({name:d.get('name')}))}><label>Yangi filial<input name="name" required/></label><button disabled={busy}>Qo‘shish</button></form></section>
<section><h2>To‘lov usullari</h2>{methods.map(m=><p key={m.id}>{m.label} <small>{m.key}</small></p>)}<form onSubmit={e=>{const d=new FormData(e.currentTarget);send(e,'/settings/payment-methods/'+encodeURIComponent(String(d.get('key'))),x=>({key:x.get('key'),label:x.get('label')}))}}><label>Kalit<input name="key" pattern="[A-Z0-9_]+" placeholder="UZCARD_QR" required/></label><label>Nomi<input name="label" required/></label><button disabled={busy}>Saqlash</button></form></section>
<section><h2>Xabar shabloni</h2>{templates.map(t=><p key={t.id}>{t.type} · {t.channel}</p>)}<form onSubmit={e=>{const d=new FormData(e.currentTarget);send(e,'/settings/notifications/'+d.get('type')+'/'+d.get('channel'),x=>({body:x.get('body'),active:true}))}}><label>Hodisa<select name="type">{['ORDER_RECEIVED','ORDER_WAITING_CUSTOMER_APPROVAL','ORDER_WAITING_PART','REPAIR_STARTED','ORDER_READY','ORDER_DELIVERED','WARRANTY_CREATED'].map(x=><option key={x}>{x}</option>)}</select></label><label>Kanal<select name="channel"><option>TELEGRAM</option><option>SMS</option></select></label><label>Matn<textarea name="body" required placeholder="{{customer_name}}, {{order_number}}, {{status}}, {{link}}"/></label><button disabled={busy}>Shablonni saqlash</button></form></section>
<section><h2>Audit</h2><div className="audit-list">{audit.slice(0,30).map(x=><p key={x.id}><strong>{x.action}</strong><small>{new Date(x.createdAt).toLocaleString('uz-UZ')} · {x.entityId}</small></p>)}</div></section></div></main>}