'use client';
import{useEffect,useState,type FormEvent}from'react';import{useRouter}from'next/navigation';import{platformApi}from'./lib';
type Plan={id:string;name:string;maxBranches:number|null;maxStaff:number|null;monthlyOrders:number|null;monthlyPrice:string};
type Org={id:string;name:string;slug:string;_count:{users:number;branches:number;orders:number};subscription:{status:string;expiresAt:string;plan:Plan}|null};
export default function Page(){const router=useRouter();const[plans,setPlans]=useState<Plan[]>([]);const[orgs,setOrgs]=useState<Org[]>([]);const[system,setSystem]=useState<Record<string,unknown>>({});const[analytics,setAnalytics]=useState<Record<string,unknown>>({});const[error,setError]=useState('');const[busy,setBusy]=useState(false);
function fail(e:unknown){if(e instanceof Error&&e.message==='SESSION_EXPIRED')router.replace('/platform/login');else setError(e instanceof Error?e.message:'Xato')}
async function load(){setPlans(await platformApi('/plans'));setOrgs(await platformApi('/organizations'));setSystem(await platformApi('/system'));setAnalytics(await platformApi('/analytics'))}
useEffect(()=>{load().catch(fail)},[]);
async function createPlan(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,d=new FormData(form);setBusy(true);try{await platformApi('/plans',{method:'POST',body:JSON.stringify({name:d.get('name'),maxBranches:Number(d.get('maxBranches'))||undefined,maxStaff:Number(d.get('maxStaff'))||undefined,monthlyOrders:Number(d.get('monthlyOrders'))||undefined,monthlyPrice:String(d.get('monthlyPrice')||'0'),features:{inventory:true,multi_branch:d.get('multi_branch')==='on',telegram:d.get('telegram')==='on',sms:d.get('sms')==='on',advanced_reports:d.get('advanced_reports')==='on',staff_commission:d.get('staff_commission')==='on',exports:d.get('exports')==='on'}})});form.reset();await load()}catch(e){fail(e)}finally{setBusy(false)}}
async function onboard(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,d=new FormData(form);setBusy(true);try{await platformApi('/organizations',{method:'POST',body:JSON.stringify(Object.fromEntries(d))});form.reset();await load()}catch(e){fail(e)}finally{setBusy(false)}}
return <main className="page"><header><span className="brand">MY SERVICE PLATFORM</span><button className="secondary" onClick={()=>{sessionStorage.removeItem('platform_token');router.replace('/platform/login')}}>Chiqish</button></header><h1>Platform boshqaruvi</h1>{error&&<p className="error">{error}</p>}<div className="cards">{Object.entries({...system,...analytics}).map(([k,v])=><section key={k}><span className="muted">{k}</span><strong>{k==='mrr'?Number(v).toLocaleString('uz-UZ'):String(v)}</strong></section>)}</div>
<div className="detail-grid"><section><h2>Servislar</h2><div className="table-scroll"><table><thead><tr><th>Servis</th><th>Tarif</th><th>Xodim</th><th>Buyurtma</th></tr></thead><tbody>{orgs.map(o=><tr key={o.id}><td>{o.name}<small>{o.slug}</small></td><td>{o.subscription?.plan.name??'—'}<small>{o.subscription?.status}</small></td><td>{o._count.users}</td><td>{o._count.orders}</td></tr>)}</tbody></table></div></section>
<section><h2>Yangi servis</h2><form onSubmit={onboard}><label>Servis nomi<input name="name" required/></label><label>Slug<input name="slug" pattern="[a-z0-9-]{3,64}" required/></label><label>Tarif<select name="planId">{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Owner ismi<input name="ownerName" required/></label><label>Telefon<input name="phone" placeholder="+998901234567" required/></label><label>Login<input name="login" required/></label><label>Vaqtinchalik parol<input name="temporaryPassword" type="password" minLength={12} required/></label><button disabled={busy}>Servis yaratish</button></form></section>
<section><h2>Yangi tarif</h2><form onSubmit={createPlan}><label>Nomi<input name="name" required/></label><label>Filial limiti<input name="maxBranches" type="number" min="1"/></label><label>Xodim limiti<input name="maxStaff" type="number" min="1"/></label><label>Oylik buyurtma<input name="monthlyOrders" type="number" min="1"/></label><label>Oylik narx<input name="monthlyPrice" type="number" min="0" step=".01" defaultValue="0"/></label><label className="check"><input type="checkbox" name="multi_branch"/>Ko‘p filial</label><label className="check"><input type="checkbox" name="telegram"/>Telegram</label><label className="check"><input type="checkbox" name="sms"/>SMS</label><label className="check"><input type="checkbox" name="advanced_reports"/>Kengaytirilgan hisobot</label><label className="check"><input type="checkbox" name="staff_commission"/>Usta komissiyasi</label><label className="check"><input type="checkbox" name="exports"/>Eksport</label><button disabled={busy}>Tarif yaratish</button></form></section></div></main>}