CREATE TABLE "TechnicianCompensation" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"userId" TEXT NOT NULL,"type" TEXT NOT NULL CHECK ("type" IN ('SALARY','PERCENTAGE','FIXED_PER_JOB','SALARY_PLUS_PERCENTAGE')),"salary" DECIMAL(18,2),"percentage" DECIMAL(5,2),"fixedPerJob" DECIMAL(18,2),"effectiveFrom" TIMESTAMP(3) NOT NULL,"effectiveTo" TIMESTAMP(3),FOREIGN KEY("organizationId","userId") REFERENCES "User"("organizationId","id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE INDEX "TechnicianCompensation_organizationId_userId_effectiveFrom_idx" ON "TechnicianCompensation"("organizationId","userId","effectiveFrom");
CREATE UNIQUE INDEX "TechnicianCompensation_one_current" ON "TechnicianCompensation"("organizationId","userId") WHERE "effectiveTo" IS NULL;
CREATE TABLE "RepairAction" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"orderId" TEXT NOT NULL,"userId" TEXT NOT NULL,"description" TEXT NOT NULL,"laborAmount" DECIMAL(18,2) NOT NULL CHECK ("laborAmount">=0),"completedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY("organizationId","orderId") REFERENCES "Order"("organizationId","id") ON DELETE RESTRICT ON UPDATE CASCADE,FOREIGN KEY("organizationId","userId") REFERENCES "User"("organizationId","id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE INDEX "RepairAction_organizationId_orderId_userId_idx" ON "RepairAction"("organizationId","orderId","userId");
CREATE TABLE "CommissionEntry" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"orderId" TEXT NOT NULL,"userId" TEXT NOT NULL,"amount" DECIMAL(18,2) NOT NULL CHECK ("amount">=0),"ruleSnapshot" JSONB NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE("organizationId","orderId","userId"),FOREIGN KEY("organizationId","orderId") REFERENCES "Order"("organizationId","id") ON DELETE RESTRICT ON UPDATE CASCADE,FOREIGN KEY("organizationId","userId") REFERENCES "User"("organizationId","id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE INDEX "CommissionEntry_organizationId_userId_createdAt_idx" ON "CommissionEntry"("organizationId","userId","createdAt");
CREATE TABLE "NotificationTemplate" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"type" TEXT NOT NULL,"channel" TEXT NOT NULL,"body" TEXT NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,UNIQUE("organizationId","type","channel"));
CREATE TABLE "PaymentMethod" ("id" TEXT PRIMARY KEY,"organizationId" TEXT NOT NULL,"key" TEXT NOT NULL,"label" TEXT NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,UNIQUE("organizationId","key"));
